version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  vue:
    build:
      context: .
      dockerfile: Dockerfile-vue
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - django

  redis:
    image: redis
    ports:
      - "6379:6379"
