# Generated by Django 4.2.2 on 2024-03-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField()),
                ('Time', models.TimeField()),
                ('Resource_Name', models.CharField(max_length=200)),
                ('Header', models.CharField(blank=True, max_length=200, null=True)),
                ('Text', models.TextField(blank=True, null=True)),
                ('Comments_Count', models.IntegerField(blank=True, null=True)),
                ('Views', models.IntegerField(blank=True, null=True)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Count_Positive_Reactions', models.IntegerField(blank=True, null=True)),
                ('Count_Negative_Reactions', models.IntegerField(blank=True, null=True)),
                ('Reposts', models.IntegerField(blank=True, null=True)),
                ('Comment_Text', models.TextField(blank=True, null=True)),
                ('Type', models.CharField(max_length=100)),
                ('Garbage', models.BooleanField(null=True)),
                ('Healthcare', models.BooleanField(null=True)),
                ('Housing_and_Public_Utilities', models.BooleanField(null=True)),
                ('Education', models.BooleanField(null=True)),
                ('Infrastructure', models.BooleanField(null=True)),
                ('Culture', models.BooleanField(null=True)),
                ('Environmental_Conditions', models.BooleanField(null=True)),
                ('Social_Security', models.BooleanField(null=True)),
                ('Politics', models.BooleanField(null=True)),
                ('Safety', models.BooleanField(null=True)),
                ('Availability_of_Goods_and_Services', models.BooleanField(null=True)),
                ('Official_Statements', models.BooleanField(null=True)),
                ('Tourism', models.BooleanField(null=True)),
                ('Facts', models.BooleanField(null=True)),
                ('Positive', models.BooleanField(null=True)),
                ('Negative', models.BooleanField(null=True)),
                ('Neutral', models.BooleanField(null=True)),
            ],
        ),
    ]
