# Generated by Django 5.0.4 on 2024-06-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.CharField(max_length=200)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('text', models.TextField(blank=True, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('type_text', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('tonality', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.region')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.resource')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.source')),
            ],
        ),
    ]
