# Generated by Django 5.0.4 on 2024-06-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_region_description_alter_region_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='subject_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
