# Generated by Django 5.0.4 on 2024-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_region_latitude_alter_region_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
