name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest

    - name: Build and push frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest ./frontend_two
        docker push ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Remove old backend image
          sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest || true
          # Remove old frontend image
          sudo docker image rm ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest || true

          # Pull updated images
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myproject-backend:latest
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myproject-frontend:latest

          # Stop and remove running containers
          sudo docker-compose -f /home/tomeo/qoliru/docker-compose.yml down

          # Start new containers
          sudo docker-compose -f /home/tomeo/qoliru/docker-compose.yml up -d
